import './globals.scss'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel='shortcut icon' href='/fevicon.ico'/>
      <title>Aman.dev</title>
      <body className={inter.className} suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
